const category = "CATEGORY";

// GET PRODUCTS
export const GET_CATEGORIES_STARTED = `${category}__GET_CATEGORIES_STARTED`;
export const GET_CATEGORIES_SUCCESS = `${category}__GET_CATEGORIES_SUCCEEDED`;
export const GET_CATEGORIES_ERROR = `${category}__GET_CATEGORIES_FAILED`;
export const GET_CATEGORIES_RESET = `${category}__GET_CATEGORIES_RESET`;

//SET CURRENT PRODUCT
export const SET_CURRENT_CATEGORY = `${category}__SET_CURRENT_CATEGORY`;
