const category = "CATEGORY";

// GET PRODUCTS
export const GET_CATEGORIES_STARTED = `${category}__GET_CATEGORIES_STARTED`;
export const GET_CATEGORIES_SUCCESS = `${category}__GET_CATEGORIES_SUCCEEDED`;
export const GET_CATEGORIES_ERROR = `${category}__GET_CATEGORIES_FAILED`;
export const GET_CATEGORIES_RESET = `${category}__GET_CATEGORIES_RESET`;

//SET CURRENT PRODUCT
export const SET_CURRENT_CATEGORY = `${category}__SET_CURRENT_CATEGORY`;

//ADD CATEGORY
export const ADD_CATEGORIES_STARTED = `${category}__ADD_CATEGORIES_STARTED`;
export const ADD_CATEGORIES_SUCCESS = `${category}__ADD_CATEGORIES_SUCCEEDED`;
export const ADD_CATEGORIES_ERROR = `${category}__ADD_CATEGORIES_FAILED`;
export const ADD_CATEGORIES_RESET = `${category}__ADD_CATEGORIES_RESET`;

//EDIT CATEGORY
export const EDIT_CATEGORIES_STARTED = `${category}__EDIT_CATEGORIES_STARTED`;
export const EDIT_CATEGORIES_SUCCESS = `${category}__EDIT_CATEGORIES_SUCCEEDED`;
export const EDIT_CATEGORIES_ERROR = `${category}__EDIT_CATEGORIES_FAILED`;

//DELETE CATEGORY
export const DELETE_CATEGORY_STARTED = `${category}__DELETE_CATEGORY_STARTED`;
export const DELETE_CATEGORY_SUCCESS = `${category}__DELETE_CATEGORY_SUCCEEDED`;
export const DELETE_CATEGORY_ERROR = `${category}__DELETE_CATEGORY_FAILED`;
