export const Colors = {
  primary: "#0764bb",
  white: "white",
  paragraphColor: "#575757",
  navy: "#092256",
  black: "black",
  background: "#f9f9f9",
  red: "red",
  gray: "gray",
  green: "green",
  lightGray: "#D3D3D3",
  shadowColor: "#171717",
  successLight: "#DAF5EC",
  errorLight: "#FFD9DE",
  default: "#BDC7D1",
};
